### ISSUE TITLE
kMS flux suppression/absorption

### ISSUE THREAD

**Issue by ktrehaeven** [ktrehaeven/Shapley#1]
**Discussion**

I'm trying to find the best way to limit flux suppression/absorption. As seen in the first image (mosaic 2gc on left, mosaic 3gc on right), the diffuse flux surrounding the strong head-tail radio source reduces in intensity after applying basic kMS solutions. I solved with the KAFCA solver and for 5min time intervals and 32 freq channels. MOSAIC 2GC vs 3GC:
![mosaic_2gc_vs_3gc](https://github.com/ktrehaeven/Shapely/assets/77777044/f86a9ab7-18bf-4546-983f-55c1e2809c3d)

To test different methods of solving this issue, I've averaged one pointing to 256 channels and a 32s dump rate and derived a deep-ish skymodel after DI selfcal. I show the averaged single pointing 2gc vs 3gc image for reference with similar kms options as before but with `dt 15 NChanSols 16` - I also attach the kms log for reference. The suppression is harder to see in the averaged images but still visible. AVERAGED 2GC VS 3GC:
![averaged_2gc_vs_3gc](https://github.com/ktrehaeven/Shapely/assets/77777044/4d02b2c0-a33c-4f01-8a61-23c9702ce343)
[log-single.ddcal-1.kms.txt.txt](https://github.com/ktrehaeven/Shapely/files/12837832/log-single.ddcal-1.kms.txt.txt)

I tried feeding kms the DDF output weight column `--Weight-OutColName` from the DI skymodel derivation step so to downweight the shortest baselines during the solve but that didn't really improve the suppression/absorption. AVERAGED 2GC VS 3GC WITH DDF WEIGHT:
![averaged_2gc_vs_3gc_with_DDF_weight](https://github.com/ktrehaeven/Shapely/assets/77777044/11f98624-6b51-4cdb-96bb-9f352cbeaee5)

Then I tried replacing this option with the `--UVMinMax [0.15, 2000]`, effectively removing the baselines <150m from the solve. This did improve the amount of suppression and gives a better noise than the weight column approach.AVERAGED 2GC VS 3GC WITH UVMINMAX=[0.15, 2000]:
![averaged_2gc_vs_3gc_uvminmax](https://github.com/ktrehaeven/Shapely/assets/77777044/c46e08e8-1656-4f7b-8ed4-4624e3441edb)
 
Am now trying different combinations of weight column and UVMinMax

**Comment by cyriltasse** [comment]
Very intersting! We coulld also try to use the constrained solver...

What do you mean by "average"?

**Comment by ktrehaeven** [comment]
@Tasse Cyril ***@***.***> I took the cross calibrated data with
its default 8s dump rate and 4096 channels and used casa mstransform to bin
each 4 integrations together, resulting in a 32s dump rate, and each 16
channels together, resulting in 256 channels. Imaged and did DI selfcal on
this 'averaged' data and this CORRECTED_DATA data is what I'm inputting
into kms.

Kind regards
Keegan Trehaeven

**Comment by ktrehaeven** [comment]
@cyriltasse It seems that if you use the ddf weight column AND a uv cut, then the level of absorption doesn't really improve and the noise increases slightly. So from my testing, just using `--UVMinMax [x, 2000]` where x is anything near ~0.15 or ~0.25 gives the best result in the averaged data. trying with the full, unaveraged data now. Fingers crossed.

**Comment by ktrehaeven** [comment]
Above confirmed. uvcut eliminates suppression/absorption
